### ISSUE TITLE
Fix characteristic group filter on import tab

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#140]
The Characteristic Group filter on the data import tab should allow for multiple selections (see WQP example below). It currently only allows the user to select one.

<img width="236" alt="image" src="https://github.com/USEPA/TADAShiny/assets/46969696/8091b236-ac86-4e1c-b722-4f38ca73a9a0">

**Comment by JamesBisese** [comment]
This is done on my computer.  

Added `multiple = TRUE` where widget UI is created, then changed test where input is prepared for submission 
Changed test from `length(input$chargroup)` == 0 to this `is.null(input$chargroup)`

**Comment by JamesBisese** [comment]
Testing

Date range 2018-05-01 to 2018-05-31
Set Characteristic Group 'Biological'
Your dataset contains 444 unique results from 89 monitoring location(s) and 7 unique organization(s).

Set Characteristic Group 'Biological' and 'Physical'
... runs forever, but does not crash
... eventually I closed the browser rather than wait for a huge dataset to be loaded.

Date range 2018-05-01 to 2018-05-02
Set Characteristic Group 'Biological', 'Sediment'
Your dataset contains 125 unique results from 59 monitoring location(s) and 14 unique organization(s).

Date range 2018-05-01 to 2018-05-02
Set Characteristic Group 'Biological'
Your dataset contains 4 unique results from 4 monitoring location(s) and 1 unique organization(s).

Date range 2018-05-01 to 2018-05-02
Set Characteristic Group 'Sediment'
Your dataset contains 121 unique results from 55 monitoring location(s) and 14 unique organization(s).

Date range 2018-05-01 to 2018-05-02
Set Characteristic Group  (leave blank)
... runs a long time, but does not crash when no Characteristic Group filter is applied.
Your dataset contains 115,971 unique results from 4,170 monitoring location(s) and 203 unique organization(s).
