### ISSUE TITLE
Custom EPA CSS conflicts with usability of leaflet, plotly

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADAShiny#52]
**Describe the bug**
The leaflet map in the overview page is hard to drag and zoom in to. The points appear to move in a delayed fashion when zooming in/out panning. Additionally, in plotly plots, the hover info flies in from the left of the plot, and the text becomes separated from the bubble, flying to varying heights above the bubble itself.

**To Reproduce**
1. Start Shiny app
2. Upload example data
3. Go to overview map and try zooming or grabbing the map and dragging, go to Explore page and build some plotly figures and try hovering over a point or box.

**Expected behavior**
Map should update more quickly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This is a problem with some of the styling contained here: https://www.epa.gov/themes/epa_theme/css/styles.css?r6lsex
This css info is contained on line 94 of the epa_markup.R file: https://github.com/USEPA/TADAShiny/blob/develop/R/epa_markup.R

**Comment by ehinman** [comment]
From Brad and Kiki - https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template This is the theme template we should use. I tried substituting it into shiny and was having issues. I'm sure someone could handily make this change!

**Comment by cristinamullin** [comment]
Commenting out following line in epa_markup.R file (for now):
```
# commenting out because of plotly conflicts. for future debugging, note that js files also tend to cause issues - Hui discussion)
# tags$link(rel = "stylesheet", media = "all", href = "https://www.epa.gov/themes/epa_theme/css/styles.css?r6lsex"),
```

Updating following lines with new template Brad provided:

```
# tags$meta(property = "og:url", content = "https://www.epa.gov/themes/epa_theme/pattern-lab/.markup-only.html"),
# tags$link(rel = "canonical", href = "https://www.epa.gov/themes/epa_theme/pattern-lab/.markup-only.html"),
# tags$link(rel = "shortlink", href = "https://www.epa.gov/themes/epa_theme/pattern-lab/.markup-only.html"),
# tags$meta(property = "og:url", content = "https://www.epa.gov/themes/epa_theme/pattern-lab/.markup-only.html"),
tags$meta(property = "og:url", content = "https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template"),
tags$link(rel = "canonical", href = "https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template"),
tags$link(rel = "shortlink", href = "https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template"),
tags$meta(property = "og:url", content = "https://www.epa.gov/themes/epa_theme/pattern-lab/?p=pages-standalone-template"),
```

**Comment by cristinamullin** [comment]
Here is the current state of this issue:

This issue is related to the EPA banner. I have tried to fix on my own but it requires CSS/HTML and R Shiny experience to troubleshoot. 
•	[fix-epa-style](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSEPA%2FTADAShiny%2Ftree%2Ffix-epa-style&data=05%7C01%7CThawley.Michelle%40epa.gov%7Ceb2021cd10274abc63f508dbcb355dfa%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C638327202294660447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q5%2FKaisc3yrZh%2B0aBHNE5ElUWvVyZ6oB9b5cQFbjpHc%3D&reserved=0) uses the current styles.css file downloaded from here: https://www.epa.gov/themes/epa_theme/pattern-lab/patterns/pages-standalone-template/pages-standalone-template.rendered.html. 
o	In this version, plotly and leaflet maps and plots do not work correctly unless I remove the .css file completely.  Because this is the case even on my laptop, I think we can rule-out any buildtime or containerization issues.  The culprit may be the sequencing of when the overall page styles are computed on page load versus when the styles invoked by leaflet and plotly are computed. 

- We may be able to edit the css file to fix this issue. ... or We might be able to sidestep this issue by having ERG create a basic HTML page, apply the EPA header/footer/etc to that page, and then embed the app's UI within an HTML <frame> element within that page.  Doing so would separate the two sources of styles (I think).
