### ISSUE TITLE
Bug - Explore tab

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADAShiny#94]
**Describe the bug**

Explore tab: Users may not be aware that they can only select sites that have both characteristics to plot both on the same chart. Users must use the map to find and select sites when using this feature. If not, they may get an error. Suggest to include a more specific error message to help users learn how/why they are not using the tab correctly & what the requirements are. Alternatively, only show sites on map and in drop down that have data with BOTH characteristics. 

**To Reproduce**

1\. Go to 'Load tab. Query Organization "FTBLKNAP" for time period "2021-09-05" to "2023-09-05". Run query.

2\. Run flag functions. Apply censored data substitutions, harmonize synonyms, and calculate TN and TP. 

3\. Go to Explore Tab. Click Generate Groups. Select Dissolved Oxygen (DO) MG/L and PH. Click "Generate Map". Select a single site: FTBLKNAP-MM-MRV-04. Click Generate Plots. You should get the error below. 

Now try this site: FTBLKNAP-PC-SGCR-02 (it should work), This suggests to me that this is user error (selecting site that does not have both Characteristics selected.). A user must first select the Characteristics (1 or 2), and then if two are selected, they MUST pick a site that has data for BOTH selected charactersitics.

FTBLKNAP-PC-LDPCR-01 (does not work)

4\. See error
Error result would be too long a vector.
![image](https://github.com/USEPA/TADAShiny/assets/46969696/fa41059a-cf1c-4c96-ae76-f362b5f283e7)

In console:
Warning: Error in :: result would be too long a vector
  106: TADA::TADA_Boxplot
  103: ::
plotly
renderPlotly [C:/Users/cmulli01/TADARShiny/TADAShiny/R/mod_figures.R#266]
  102: func
   99: shinyRenderWidget
   98: func
   85: renderFunc
   84: output$figures_1-boxplot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in :: result would be too long a vector
  106: TADA::TADA_Histogram
  103: ::
plotly
renderPlotly [C:/Users/cmulli01/TADARShiny/TADAShiny/R/mod_figures.R#272]
  102: func
   99: shinyRenderWidget
   98: func
   85: renderFunc
   84: output$figures_1-histogram
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Warning: Error in :: result would be too long a vector
  105: plotly::layout
  103: ::
plotly
renderPlotly [C:/Users/cmulli01/TADARShiny/TADAShiny/R/mod_figures.R#257]
  102: func
   99: shinyRenderWidget
   98: func
   85: renderFunc
   84: output$figures_1-scatter
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>

![image](https://github.com/USEPA/TADAShiny/assets/46969696/ddc2249a-02ef-4c8e-b39c-e0005991258a)

**Comment by cristinamullin** [comment]
This bug goes beyond the scenario above. 

Selena tested the application and ran into the same error with a different dataset. 

Steps:
1. Query Org PUEBLO_POJOAQUE for Oct 1 2021-2022
2. Run flag tests
3. Go to explore tab. Generate groups. Select pH. Generate Map for all sites. Then choose only 1 site and generate map (works OK). Then choose the other site and click generate map (see same error as above- Error in :: result would be too long a vector). Going from all sites to one site is OK, but going to the next site after that does not work. IF you reset to ALL sites, then go back to the other single site, it will work. You must rest with all sites before going to the next single site... cannot go from single site to single site.

From Selena:
Here are the screenshots I took for the error I was receiving: 
 
![image](https://github.com/USEPA/TADAShiny/assets/46969696/68f3d89d-ca0c-4bc8-9f20-b4f5851a733a)

 
Cannot go from one site to the next site, it gives an error. 
 
![image](https://github.com/USEPA/TADAShiny/assets/46969696/fd7eccaf-15d2-457d-97de-22583efa61bc)

 
But if go back to all sites: 
 
 
![image](https://github.com/USEPA/TADAShiny/assets/46969696/ee0ca0e7-b0c5-4256-8f7d-0c857de0a8dd)

 
THEN can move to next site

![image](https://github.com/USEPA/TADAShiny/assets/46969696/136dc648-8609-42ff-9a7d-80cdd7ab45f0)

**Comment by elisehinman** [comment]
@cristinamullin An issue here is that the site dropdown below the map contains ALL the sites in the MAP. However, the single-characteristic plots (first tab) ONLY show the FIRST characteristic selected for mapping (in your first example, DO). Because there are sites with ONLY PH, if a user selects a site with ONLY PH, it will throw an error, because it's looking for DO to plot. This was not well articulated in the text for the figures (apologies).

Options that I see:
(1) each plot tab has its OWN drop down to select sites, where the single scatterplot could also have a characteristic drop down (for the FTBELKNAP example, DO or PH would show up in the drop down) that dictates what shows up in the site drop down. The two-characteristic scatterplot would only have a site drop-down for sites with BOTH characteristics (e.g. PH and DO).
(2) one drop down that shows sites that have either (a) the first characteristic selected or (b) both characteristics selected, and the two-characteristic scatterplot only shows up when the site(s) has/have both characteristics. The drop down could have the name of the site and then in parentheses what characteristic(s) is/are present at that site (e.g. DO and PH, DO only, or PH only). 
(3) keep as-is, maybe add the site-specific characteristics in parentheses as mentioned in (2), but when the selected site does not have the first characteristic, a message could pop up that says "The site you selected was not sampled for [first characteristic], please select sites that have [first characteristic].
(4)** Make it so that user selects site(s) from map, single-characteristic scatterplot appears with a drop down for characteristic, and two-characteristic scatterplot appears when site(s) have both characteristics.

** would take more coding/shiny knowledge than the other options, but I think is probably one of the clearer paths forward. The challenge is that the user might want to use characteristic(s) to understand sites on a map, or they might want to use sites on a map to understand characteristic(s). I thought for a little while that if the user didn't pick a characteristic, then the map would show all the sites. If they picked a/two characteristic(s), they could compare sites on a map. Then they'd use the sites on the map to 

I think something I struggled with in this tab was the most likely way people would want to review data. I figured that people would use the map to decide which site/characteristic they wanted to plot/review, but I'm not sure if that matches reality. I didn't have time to implement the situation where someone would select a site on the map, and it would show up in the plot(s) below. 

Another thing people might want to see is a site comparison for a single characteristic. This would require a scatterplot/histogram/boxplot function that would accommodate multiple sites. Could be a future feature.

**Comment by elisehinman** [comment]
Selena found a bug in the code! I submitted a PR that fixes Selena's discovery and implements option (3) from above message. This is a short term solution, but I think the explore tab could use more rethinking/opinions -- this will improve its usability.

**Comment by cristinamullin** [comment]
I reviewed your edits and it seems to be working great now. I'll hold onto these other suggestions. Thank you very much for your help!
